/**
 * data.js — Catálogo de capas KML · Zona Metropolitana del Valle de Toluca
 *
 * driveUrl = https://drive.google.com/uc?id=ID&export=download
 */
window.CAPAS = [

  /* ── LÍMITES Y CONTORNOS ─────────────────────────────── */
  { id:"delegaciones",      titulo:"Delegaciones",            grupo:"Límites y Contornos", tema:"limites",    escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Polígonos de delegaciones del municipio de Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=18L_CgtW-o8VmbBVZ7rW4yIC8ziTWFUMS&export=download", icon:"🗂" },
  { id:"zmvt-contorno",     titulo:"ZMVT Contorno",           grupo:"Límites y Contornos", tema:"limites",    escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Contorno de la Zona Metropolitana del Valle de Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1lERjzNkjl8SNIa1xDE23u20w45-fDcQ3&export=download", icon:"🗺" },
  { id:"poligono-contorno", titulo:"Polígono Contorno",       grupo:"Límites y Contornos", tema:"limites",    escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Polígono de contorno del área de estudio.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1USz5Ll5nhTAaWU8Sgm6ouAY6ZMNo8stT&export=download", icon:"🔷" },
  { id:"toluca",            titulo:"Toluca",                  grupo:"Límites y Contornos", tema:"limites",    escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Límite municipal de Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1n-Dn7IgCRI8ZsTri5xo9b7M0qnO6J38t&export=download", icon:"🏙" },
  { id:"zmvt",              titulo:"ZMVT",                    grupo:"Límites y Contornos", tema:"limites",    escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Zona Metropolitana del Valle de Toluca completa.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1ode4RsSdS4D44lS7U_o8wRTEtkOl-9Yc&export=download", icon:"🗾" },
  { id:"toluca-manzanas",   titulo:"Toluca Manzanas",         grupo:"Límites y Contornos", tema:"limites",    escala:"localidad", fuente:"INEGI", fecha:"2020", desc:"Manzanas censales del municipio de Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1GnGhVqLAKgUKw6q0UzT12a0CdqLkvF2l&export=download", icon:"🏘" },
  { id:"metropolis-2020",   titulo:"Metrópolis 2020",         grupo:"Límites y Contornos", tema:"limites",    escala:"nacional",  fuente:"INEGI", fecha:"2020", desc:"Zonas metropolitanas de México 2020.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1NxxTEJUEyWMI3vNzt_D2bEnyibtLlaus&export=download", icon:"🌆" },
  { id:"edomex-igecem",     titulo:"EdoMex IGECEM",           grupo:"Límites y Contornos", tema:"limites",    escala:"estatal",   fuente:"IGECEM", fecha:"2022", desc:"División municipal del Estado de México según IGECEM.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1WFg3Q0xTCzf6ff8dqqxqbuMWER_1GrU7&export=download", icon:"📐" },

  /* ── TRANSPORTE PÚBLICO ──────────────────────────────── */
  { id:"rutas-toluca-main", titulo:"Rutas de Toluca",         grupo:"Transporte Público", tema:"transporte",  escala:"municipal", fuente:"Propio", fecha:"2026", desc:"Red de rutas de transporte público concesionado en Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1-lR1RLk1xjUQS099g81ahYz2xzjNUJ-4&export=download", icon:"🚌" },
  { id:"cableus",           titulo:"Cableús Líneas",          grupo:"Transporte Público", tema:"transporte",  escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Trazado de las líneas del sistema Cableús en Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1n5DaIvhAxyAMt86XLcnwZXr5xG7YxvDq&export=download", icon:"🚡" },
  { id:"tren-interurbano",  titulo:"Tren Interurbano",        grupo:"Transporte Público", tema:"transporte",  escala:"estatal",   fuente:"Propio", fecha:"2024", desc:"Trazo del Tren Interurbano México-Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1TxlxahLt5RKM_W86RqMyyAwvvLRua8pz&export=download", icon:"🚆" },
  { id:"rutas-toluca",      titulo:"Rutas Toluca (Alt.)",     grupo:"Transporte Público", tema:"transporte",  escala:"municipal", fuente:"Propio", fecha:"2026", desc:"Versión alternativa de la red de rutas.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1lvUIrPhAkVWDCy45a1PMqAjPRAIOmXdL&export=download", icon:"🗺" },
  { id:"terminal-completo", titulo:"Terminal Toluca Rutas",   grupo:"Transporte Público", tema:"transporte",  escala:"municipal", fuente:"Propio", fecha:"2026", desc:"Rutas completas desde la Terminal de Autobuses de Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1Yut7c9Gdfk4tMvs_ybkkyVs-1Zi35HCT&export=download", icon:"🏢" },
  { id:"cetram-rutas",      titulo:"CETRAM Rutas",            grupo:"Transporte Público", tema:"transporte",  escala:"municipal", fuente:"Propio", fecha:"2026", desc:"Rutas que conectan al CETRAM.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1l14vL1AXLX0gIGN1NudBp4_K7mtESvq-&export=download", icon:"🔄" },
  { id:"rutas-uber",        titulo:"Rutas Uber",              grupo:"Transporte Público", tema:"transporte",  escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Zonas y rutas relevantes para servicios de Uber en la ZMVT.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1Qf7HvaYZJaygaiEfC9LgQItZx-U5QalQ&export=download", icon:"🚗" },

  /* ── RUTAS REALES ────────────────────────────────────── */
  { id:"rutas-reales-toluca",  titulo:"Rutas Reales Toluca",       grupo:"Rutas Reales", tema:"transporte", escala:"municipal", fuente:"Propio", fecha:"2026", desc:"Trazado real verificado en campo de rutas en Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1gg14q_yy0khlFEjdxx6f8Zu25qW11kJM&export=download", icon:"✅" },
  { id:"rutas-reales-lerma",   titulo:"Rutas Reales Lerma",        grupo:"Rutas Reales", tema:"transporte", escala:"municipal", fuente:"Propio", fecha:"2026", desc:"Trazado real verificado en campo de rutas en Lerma.", thumb:"", driveUrl:"https://drive.google.com/uc?id=14NyoCr4N1ihRYQgo4cbTNY-ii4ZVl8Oi&export=download", icon:"✅" },
  { id:"rutas-reales-zinac",   titulo:"Rutas Reales Zinacantepec", grupo:"Rutas Reales", tema:"transporte", escala:"municipal", fuente:"Propio", fecha:"2026", desc:"Trazado real verificado en campo de rutas en Zinacantepec.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1Z5R1gkR0Iu_Rmg7_bawiuE1-3AaV_4F0&export=download", icon:"✅" },

  /* ── VIALIDADES ──────────────────────────────────────── */
  { id:"vias-toluca-igecem",  titulo:"Vías Toluca IGECEM",  grupo:"Vialidades", tema:"infraestructura", escala:"municipal", fuente:"IGECEM", fecha:"2022", desc:"Red vial del municipio de Toluca según IGECEM.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1tF1KnocM_5R48w5S8iPFLqGWQ7ffkFNZ&export=download", icon:"🛣" },
  { id:"vias-toluca",         titulo:"Vías Toluca",         grupo:"Vialidades", tema:"infraestructura", escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Red vial de Toluca levantada en campo.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1l8hImfx0sdRwjStPhYsMT9qVBg49W6Sj&export=download", icon:"🛤" },
  { id:"diagnostico",         titulo:"Diagnóstico",         grupo:"Vialidades", tema:"infraestructura", escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Capa de diagnóstico de la red de transporte.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1kg_kEJ9tLWLwVyClAcKt_Ti8wO2s4bYn&export=download", icon:"📊" },

  /* ── INTERSECCIONES ──────────────────────────────────── */
  { id:"intersec-toluca",    titulo:"Intersecciones Toluca",         grupo:"Intersecciones", tema:"infraestructura", escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Puntos de intersección del sistema de transporte en Toluca.", thumb:"", driveUrl:"https://drive.google.com/uc?id=17HMAnPyTSRLdPNuaMf9vd_FwESHlDMGj&export=download", icon:"🔀" },
  { id:"intersec-lerma",     titulo:"Intersecciones Lerma",          grupo:"Intersecciones", tema:"infraestructura", escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Puntos de intersección del sistema de transporte en Lerma.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1H16Kvl1fRiE2cAD95yXCxTPMVquvc6PX&export=download", icon:"🔀" },
  { id:"intersec-zinac",     titulo:"Intersecciones Zinacantepec",   grupo:"Intersecciones", tema:"infraestructura", escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Puntos de intersección del sistema de transporte en Zinacantepec.", thumb:"", driveUrl:"https://drive.google.com/uc?id=10u5tpWy4JRk5OY-oMxrHy647-l4uhuPL&export=download", icon:"🔀" },
  { id:"intersec-concesion", titulo:"Intersecciones Concesionarios", grupo:"Intersecciones", tema:"infraestructura", escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Intersecciones de rutas por operador concesionario.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1YWv7L-usHC3UVQqTk-qV1cjwo6Be5eVm&export=download", icon:"🔀" },
  { id:"intersecciones",     titulo:"Intersecciones General",        grupo:"Intersecciones", tema:"infraestructura", escala:"municipal", fuente:"Propio", fecha:"2024", desc:"Capa general de intersecciones de la red.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1bVRVTFsSSFamZlHOf11y1lI7v09RUiM3&export=download", icon:"🔀" },

  /* ── LOCALIDADES RECORRIDAS ──────────────────────────── */
  { id:"localidades-r",  titulo:"Localidades Recorridas",   grupo:"Localidades Recorridas", tema:"recorridos", escala:"localidad", fuente:"Propio", fecha:"2026", desc:"Localidades visitadas durante el levantamiento de campo.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1iwfX6WW6f1W0tVMNVOngp5WdkZRB6Aw0&export=download", icon:"📍" },
  { id:"localidades-1",  titulo:"Localidades Recorridas 1", grupo:"Localidades Recorridas", tema:"recorridos", escala:"localidad", fuente:"Propio", fecha:"2026", desc:"Lote 1 de localidades recorridas.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1V38fEnYaEAU5mytKL3mWxhLp91S4GHMy&export=download", icon:"📍" },
  { id:"localidades-2",  titulo:"Localidades Recorridas 2", grupo:"Localidades Recorridas", tema:"recorridos", escala:"localidad", fuente:"Propio", fecha:"2026", desc:"Lote 2 de localidades recorridas.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1g9By9xChQRZ-IQK-g5pW51Dele4CPbnK&export=download", icon:"📍" },
  { id:"localidades-3",  titulo:"Localidades Recorridas 3", grupo:"Localidades Recorridas", tema:"recorridos", escala:"localidad", fuente:"Propio", fecha:"2026", desc:"Lote 3 de localidades recorridas.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1ojgMERMrOwJCrvEmXOf1wOm1PmNx1vK0&export=download", icon:"📍" },
  { id:"localidades-4",  titulo:"Localidades Recorridas 4", grupo:"Localidades Recorridas", tema:"recorridos", escala:"localidad", fuente:"Propio", fecha:"2026", desc:"Lote 4 de localidades recorridas.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1-2uAEbv1faM-LBZcM3dRd2EERQFk7x9S&export=download", icon:"📍" },
  { id:"localidades-5",  titulo:"Localidades Recorridas 5", grupo:"Localidades Recorridas", tema:"recorridos", escala:"localidad", fuente:"Propio", fecha:"2026", desc:"Lote 5 de localidades recorridas.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1M4Co8cBsSuKLcZg0TPZ0U1s-g3e7FeCw&export=download", icon:"📍" },
  { id:"localidades-6",  titulo:"Localidades Recorridas 6", grupo:"Localidades Recorridas", tema:"recorridos", escala:"localidad", fuente:"Propio", fecha:"2026", desc:"Lote 6 de localidades recorridas.", thumb:"", driveUrl:"https://drive.google.com/uc?id=1qAasKaIfZ2Kv0AzU6OZxahHC7cMjgBph&export=download", icon:"📍" },
];
